### ISSUE TITLE
Support ruby 3.0, 3.1

### ISSUE THREAD

**Issue by Umekawa** [increments/qiita-markdown#106]
Now, qiita-markdown does not work 3.0.x.
https://github.com/increments/qiita-markdown/pull/105/checks?check_run_id=3810472533

**Comment by maedana** [comment]
I would like Ruby3.x support. So I tried to support Ruby3.x.
https://github.com/increments/qiita-markdown/pull/116

**Comment by ohakutsu** [comment]
@maedana 
Thank you for contributing!
