### ISSUE TITLE
pygments.rb v1.0.0 breaks the spec

### ISSUE THREAD

**Issue by gfx** [increments/qiita-markdown#42]
Hi, I'm maintaining https://github.com/tmm1/pygments.rb and have released pygments.rb v1.0.0 with the latest [Pygments](http://pygments.org/) (2.2.0-snapshot).

Unfortunately, Pygments (not pygments.rb but the upstream project) has incompatibility from the version shipped with pygments.rb v0.6.3, and its change breaks the spec of this gem.

I am looking into this issue in my project that uses pygments.rb, but anyway I've reported it here.

**Comment by r7kamura** [comment]
@gfx So what do you think we should do?

**Comment by gfx** [comment]
Nothing for now. Just told you the current status.

**Comment by r7kamura** [comment]
@gfx OK, thank you for your reporting 🙏 

By the way, I'll try to use [rouge](https://github.com/jneen/rouge) for syntax-highlighting in Qiita and Qiita:Team in the future. I'm using it in my other personal products and they works fine.

**Comment by gfx** [comment]
Yeah, I think rouge seems better than pygments.rb these days.

**Comment by r7kamura** [comment]
@gfx FYI, I decided to migrate from pygments.rb to rouge and just sent a Pull Request: https://github.com/increments/qiita-markdown/pull/43

The major reason of this migration is pygments.rb causes problems on thread-based web server like Puma. In our case, it raised many errors on Puma with pygments.rb on our migration from Unicorn to Puma 😩

**Comment by gfx** [comment]
Oh, that's because pygments.rb employs a daemon process for python Pygment. It can be fixed but rougue is better anyway.
