### ISSUE TITLE
Change default syntax hilighter from Pygments to Rouge

### ISSUE THREAD

**Issue by Umekawa** [increments/qiita-markdown#78]
The qiita-markdown gem uses Pygments as the default syntax highlighter, but Qiita currently uses Rouge, and Qiita Team plans to change to Rouge too soon.
Rouge also supports modern languages such as React, and has the advantage of being more stable than Pygments.rb.
Therefore, we would like to change the default syntax highlighter to Rouge, and users are encouraged to create their own filters when they continue to use Pygments.

## Ref 
- https://blog.qiita.com/171086599599-2/  (News of Qiita change syntax hilighter)
- https://github.com/rouge-ruby/rouge/wiki/List-of-supported-languages-and-lexers (Rouge support list)
- https://pygments.org/languages/ (Pygments support list)

**Comment by slonopotamus** [comment]
> has the advantage of being more stable than Pygments.rb

Could you please elaborate on this?

**Comment by Umekawa** [comment]
Pygments.rb need to python process, so we faced to the process broken error when we use this on multi thread server as Puma (Perhups, this error is problem of Puma or our environment).
Also, we want to stop having dependency python as default.
Of cource, if we will change to default syntax hilighter, we will write how to use Pygments.rb for people want to use pygments as syntax hilighter.
